### ISSUE TITLE
修改tableView中cell选中以后的背景色

### ISSUE THREAD

**Issue by jydemo** [zhihaozhang/qingmang-for-mac#3]
自定义NSTableRowView，
//改变cell选中后的背景色
    override func drawSelection(in dirtyRect: NSRect) {
        super.drawSelection(in: dirtyRect)
       var slectorRect = NSInsetRect(self.bounds, 0, 0)
        NSColor(calibratedWhite: 0.92, alpha: 1.0).setStroke()
        NSColor(calibratedWhite: 0.92, alpha: 1.0).setFill()
        var slectorPath = NSBezierPath(roundedRect: slectorRect, xRadius: 0, yRadius: 0)
        slectorPath.fill()
        slectorPath.stroke()
    }
然后实现tableview的代理方法，
func tableView(_ tableView: NSTableView, rowViewForRow row: Int) -> NSTableRowView? {
      let  rowview = MyTableRowView(frame: .zero)
        return rowview
    }

**Comment by zhihaozhang** [comment]
也可以覆盖cell.swift里的一个变量，不过我认为你的方法更好，谢谢。
override var backgroundStyle:NSBackgroundStyle{
        didSet{
            if backgroundStyle == .dark{
                self.layer?.backgroundColor = NSColor(red: 220/255, green: 220/255, blue: 220/255, alpha: 1).cgColor
            }else{
                self.layer?.backgroundColor = NSColor.white.cgColor
            }
            
        }
    }

**Comment by zhihaozhang** [comment]
I think your solution is better. Thank you so much.
